project:
  type: website
  output-dir: docs

website:
  site-url: https://www.nucleomapa.org
  title: "Núcleo MAPA"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: sobre.qmd
        text: Sobre
      - href: artigos.qmd
        text: Artigos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pt-BR