project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - assests/favicon/favicon.svg

website:
  site-url: www.nucleomapa.org
  title: "Núcleo MAPA"
  favicon: assests/favicon/favicon.svg
  navbar:
    left:
      - href: sobre.qmd
        text: Sobre
      - href: artigos.qmd
        text: Artigos
      - href: pesquisadores.qmd
        text: Pesquisadores

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pt-BR
